#spring:
#  application:
#    name: Movies-processor
#
#  cloud:
#    function:
#      definition: movieProcessor
#
#    stream:
#      bindings:
#        movieProcessor-in-0:
#          destination: movies
#
##      kafka:
##        streams:
##          binder:
##            brokers:
##              - localhost:9092
##
##            configuration:
##              application.id: movies-processor-v3
##              auto.offset.reset: earliest
##
##              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
##              default.value.serde: org.springframework.kafka.support.serializer.JacksonJsonSerde
##
##              spring.json.value.default.type: com.processor.moviesprocessor.model.Movie
##              spring.json.trusted.packages: "*"
##              spring.json.use.type.headers: false
