spring:
  application:
    name: Movies-processor
  cloud:
    function:
      definition: movieProcessor

    stream:
      bindings:
        movieProcessor-in-0:
          destination: movies
      #        movieProcessor-out-0:
      #          destination: action.movies

      kafka:
        streams:
          binder:
            brokers:
              - localhost:9092
            configuration:
              application.id: movies-processor
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
              auto.offset.reset: earliest

              spring:
                json:
                  value:
                    default:
                      type: com.processor.moviesprocessor.model.Movie
                  trusted:
                    packages: "*"
                  use:
                    type:
                      headers: false
  #              spring.json.type.mapping: >
  #                com.domain_crawler.producer.Domain:com.processor.demo.Domain

